- data-broker-validation/update-schema/tasks/main.yml
- data-broker-web-api/update-schema/tasks/main.yml
@klrBAH:  This adds the field and rule definition loads to the ansible scripts, as well as loading from the TAS file.
> Setup loads field definitions, rules, and TAS

- .gitignore
- app-base-image-installs/tasks/main.yml
- app-base-image.yml
- app-instance-image.yml
- base-image-installs-python35/tasks/main.yml
- base-image-python35.yml
- pull-repo/tasks/main.yml
- usaspending-instance-image.yml
Pulls from git instead of S3, added usaspending playbook.
> Ds 291 usaspending api

- deploy.py
this inline if statement will allow us to change the env variable for
which environment to deploy.
> FABS stable build tools

- copy-files/tasks/main.yml
edit the packer command to deploy SSL certs to FABS, and also handle
the exception if there are not certs available.
Also edited the Ansible to change the ownership of of the files for
FABS certs.
> edited the Ansible commands to account for SSL

- base-image-installs-python35/tasks/main.yml
- usaspending-deploy/usaspending-base.yml
> updated Yum package list

- deploy.tf
- usaspending-deploy/usaspending-deploy.tf
> Add env tags

- usaspending-deploy/usaspending-api-launch.yml
- usaspending-instance-image.yml
> added elastic-search endpoint env var

- usaspending-deploy/usaspending-api-launch.yml
- usaspending-instance-image.yml
This will now pull from usaspending-config (filebeat and nginx configs).
Also removes the elasticsearch stuff that was added prematurely (not in configs).
> Use usaspending config

- usaspending-deploy/usaspending-frontend.yml
This has been added in a DOMAIN variable that gets passed with Jenkins. Ready to go.
This is to add the server_name to the nginx.confs dynamically with Ansible.
> add server name, comment on required env vars

- broker-deploy/app-instance-image.yml
- broker-deploy/app-instance-launch.yml
- broker-deploy/broker-deploy.py
- broker-deploy/broker-deploy.tf
- broker-deploy/config-new-relic/tasks/main.yml
- broker-deploy/copy-files/tasks/main.yml
- broker-deploy/create-app-log/tasks/main.yml
- broker-deploy/install-requirements/tasks/main.yml
- broker-deploy/pull-repo/tasks/main.yml
- broker-deploy/sandbox-only/broker-sbx-deploy.tf
- broker-deploy/start-services/tasks/main.yml
- broker-deploy/supervisord/tasks/main.yml
After merging, will need to update:
> Broker patching pipeline updates

- usaspending-deploy/usaspending-api-launch.yml
changing filebeat yml name
associated w/ https://github.com/fedspendingtransparency/usaspending-config/pull/78
> change file name

- elasticsearch/elasticsearch-base.yml
- elasticsearch/elasticsearch-launch.yml
- updated `jvm_heap_size to 12g`
- added `nginx configs`
- Modified `SELinux` for Nginx
- Updated `uLimit`
> Elasticsearch prod

- usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml
Note: config key has already been added to appropriate secrets files on S3 for each env.
> Adding Bulk Download DB URL

- usaspending-deploy/usaspending-api-launch.yml
pulls the env vars we load in from configs together into a loop
> Environment variable organization

- download_cars_gtas.py
This is the script that Alisa previously made/updated to correct the cars_tas file for ingest. The loader job was using this version from a stale branch so we need to get the code loaded into master so the job can be updated.
> Updating downloader script

- broker-deploy/app-instance-launch.yml
this will be deployed tonight; consolidates filebeat indexes for the broker
> coincides with broker-config

- usaspending-deploy/usaspending-api-launch.yml
Adding CFDA variables per:
* https://github.com/fedspendingtransparency/usaspending-api/pull/1273
* https://github.com/fedspendingtransparency/usaspending-config/pull/224
> CFDA variables

- usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml
- usaspending-deploy/usaspending-api-launch.yml
DO NOT MERGE WITHOUT CONFIG PR
see https://github.com/fedspendingtransparency/usaspending-config/pull/232
> Ansible vars file rename

- usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml
- usaspending-deploy/usaspending-api-launch.yml
adds this field to the api and bulk downloader launches
> add USASPENDING_AWS_REGION to settings.py injects

- usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml
- usaspending-deploy/usaspending-api-launch.yml
> remove region and bucket names

- broker-deploy/app-instance-image.yml
- broker-deploy/app-instance-launch.yml
- broker-deploy/broker-deploy.py
Changes: 
app-instance-image.yml:
- Reformatted and removed `chdir` in pip module
- pulled build-tools repo
broker-deploy.py:
- added environment and extra vars to packer file
Tested with sandbox pipeline: 
http://ec2-52-222-24-126.us-gov-west-1.compute.amazonaws.com:8080/view/Broker-Backend-Deploys/job/Backend-Instance-Deploy-Sandbox/12/console
> Moving to one packer file

- broker-deploy/broker-deploy.py
Deploys fix/hotfix-broken-submissions to staging so it can go to prod.
> hotfix file d copy fix

- broker-deploy/app-instance-image.yml
- broker-deploy/broker-deploy.py
- broker-deploy/broker-deploy.tf
- usaspending-deploy/bulk-download/usaspending-bulk-download-deploy.py
- usaspending-deploy/bulk-download/usaspending-bulk-download-deploy.tf
- usaspending-deploy/usaspending-deploy.py
- usaspending-deploy/usaspending-deploy.tf
- stores terraform state files in bucket called `terraform-states`. 
- Runs terraform init within python script
- terraform files now have backend s3 block
- s3 key and bucket is stoved in tf.json in config
Tested with sandbox with usaspening-api, bulk-download, and broker.
> tfstate stored in s3

- broker-deploy/broker-deploy.py
- usaspending-deploy/bulk-download/usaspending-bulk-download-deploy.py
- usaspending-deploy/usaspending-deploy.py
Changes to usaspending, bulk-download, and broker deploy python scripts. 
Tested in usaspending usaspending sandbox and broker is tested locally (not including terraform).
> Boto --> Boto3

- cf-invalidate.py
- usaspending-deploy/invalidate-url.py
Use the profile instead of Jenkins keys, simplify setup for pipelines
> Revise deploy script

- broker-deploy/app-instance-image.yml
- usaspending-deploy/usaspending-api-image.yml
it was downloading the wrong file
> Update ansible s3 get command for broker

- broker-deploy/app-instance-launch.yml
Update app launch playbook in the broker deploy to use prod tagging instead of master.
> Change datadog tagging to use prod (not master)

- broker-deploy/broker-deploy.py
- usaspending-deploy/bulk-download/usaspending-bulk-download-deploy.py
- usaspending-deploy/usaspending-deploy.py
The argument parsing/mapping to optionsDict was...less than stellar. Cleaning it up with a single required choice arg.
> simplify argument parsing

- broker-deploy/broker-deploy.py
replace with source_ami_filter and command line vars to `packer build`
> remove packer spec update

- pull_and_rename_cars_gtas.py
production files are named PE.CARS and PE.GTAS, so specify that syntax here.
> narrow in on production files

- usaspending-deploy/usaspending-api-launch.yml
Configured usaspending-api-launch.yml to include new buildout for either Bulk-downloader or the api according to {{ BUILD_TYPE }} variable
> Committing changes to usaspending-api-launch.yml

- usaspending-deploy/usaspending-api-launch.yml
- usaspending-deploy/usaspending-deploy.py
- usaspending-deploy/usaspending-deploy.tf
Bulk downloader now included in tf file, minor clarifying comments created in python deploy file
> Updated Terraform file to include bulk-downloader vars

- usaspending-deploy/usaspending-deploy.tf
on 5000 requests in 5 minute period, will scale up, if less than 5000 after 2 intervals in a row, scale back down.
> changing asg rules to request based.

- pull_and_rename_cars_gtas.py
* "list_objects" limits the results to 1000, so instead we're using "boto3.resource" instead of "boto3.client"
> Bugfix: sf133 pull with "list_objects"

- broker-deploy/app-instance-launch.yml
- usaspending-deploy/usaspending-api-launch.yml
conventions set here: https://federal-spending-transparency.atlassian.net/browse/OPS-1226
> updating the ssl paths to match new conventions

- Dockerfile
added +x to the terragrunt executable.
> updated terragrunt executable permissions

- usaspending-deploy/usaspending-deploy.tf
Added autoscaling for bd based on sqs. Let me know if you think we need to base this on a different metrics. I enabled the ASG metrics for this and got rid of the cpu alarm.
> OPS-1001 - BD autoscaling

- Dockerfile
- requirements.yml
Locking versions to galaxy roles. I'll start removing requirements.yml from data-act-config after verifying script functionality.
> Add galaxy dockerfile

- broker-deploy/app-instance-launch.yml
Oops. Not sure why I did that. I think this should fix it.
> Enable datadog 

- broker-deploy/maintenance_page.html
> DEV-5651: Maintenance Page Design Updates

- broker-deploy/app-instance-image.yml
- broker-deploy/app-instance-launch.yml
- broker-deploy/broker-deploy.py
- updated ansible python interpreter to 3.7
- enforced config permissions to what prod currently is
- used the full path for awscli since it wasn't getting picked up during the ansible run after the pip install 
- added the symlinks for supervisord.
> Broker Python3.7 Updates

- Dockerfile
Fixes a bug when running `terragrunt plan`
> Update Terragrunt to 0.25.4

- pull_and_rename_cars_gtas.py
> Updating SF133 bucket for DTI

- pull_and_rename_cars_gtas.py
> Updating pull_and_rename_cars_gtas for staging tests, bucket params

- Dockerfile
I needed this for some more elegant error handling with boto3 when working with the rds lightswitch.
> Add botocore
