job-queue-manager/fsrs-cron/tasks/main.yml
job-queue-manager/site.yml
job-queue-manager/yum-installs/tasks/main.yml

FSRS data needs to be downloaded in chunks of 500 entries. To get us started,
this installs cron to the job manager and sets up a cron job to execute the
`loadFSRS` script. It's currently appending the results (a line or two per
run) to a tmp file, but that's only a temporary solution.
@klrBAH - this works for me on a centos vagrant box but I hacked out all of the configuration steps, so I'm not 100% positive it all works. I think you said I need to PR a separate branch, too? Also, no rush on this; whenever's convenient.

Adds FSRS bulk-loading cron job

---

job-queue-manager/fsrs-cron/tasks/main.yml

Notably:
* Don't use ansible_env.PYTHONPATH; it'll crash if PYTHONPATH isn't available
* Don't use the `env=yes` flag (prefix the command instead) to avoid potential
version issues
* Use python3 (python2 is installed as python)
* Redirect stderr to the log file as well
* Use sudo + a user to account for user mismatches
* Add the `env` var

Fix a few errors with the FSRS cron job

---

deploy.tf
usaspending-deploy/usaspending-deploy.tf

Changed the blocks to "tag" vs "tags" (escaped characters issue) and ditched the deploy timestamp to get to a fixed state. Will look at adding both back.

Fix tagging

---

broker-deploy/app-instance-launch.yml

For now, disable newrelic. We will bake a new base image once the datadog agent is tested on Broker.

remove newrelic from broker deploys

---

usaspending-deploy/usaspending-api-launch.yml

STATIC_ASSETS_URL should ignore this {{ branch }} concat nonsense and just be declared in the yml config.

Drop branch concat to static url path

---

broker-deploy/broker-deploy.py

inconsistent `DEVELOPMENT` branch vs `DEV` AMI tagging for broker

Dev branch fix

---

usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml
usaspending-deploy/usaspending-api-image.yml
usaspending-deploy/usaspending-api-launch.yml
usaspending-deploy/usaspending-deploy.py

Summary: 
Execute packer scripts with local ansible playbooks instead of copying it to the host. 
Changes: 
- change hosts variable in launch playbooks to `localhosts`
- changes in image playbooks to make it work with local packer execution
- some code clean up in deploy python scripts. 
NOTE: the build-tools branch in the image ansible playbooks needs to be removed after merging.

Remote packer execution

---

Dockerfile
broker-deploy/broker-deploy.py
usaspending-deploy/bulk-download/usaspending-bulk-download-deploy.py
usaspending-deploy/usaspending-deploy.py

The execpath is just `terraform` and `packer` now.

Change the execpath of terraform and packer

---

Dockerfile
broker-deploy/app-instance-image.yml
broker-deploy/app-instance-launch.yml

- Bug in the `aws_s3` module definition with the key path.
- Requires boto3/core installed for the ansible python version
- Datadog module code was written before remote packer execution
- Consolidated permissions
- Pulling certs from S3 using command line instead of the module, because the bucket policies are intended to ONLY access the prod or non-prod envs.

Broker deploy docker fix

---

usaspending-deploy/bulk-download/usaspending-bulk-download-launch.yml

None of the Bulk Download instances have worked in the past couple days due to the ansible script failing at this task. 
This patches that, will deploy to production.

cannot use BRANCH environment variable when it does not exist

---

usaspending-deploy/usaspending-api-launch.yml

Removing unnecessary CFDA vars.
`usaspending-api` PR:
https://github.com/fedspendingtransparency/usaspending-api/pull/1714
Wait for Sprint 78 to reach production

Remove CFDA vars

---

broker-deploy/app-instance-image.yml
usaspending-deploy/usaspending-api-image.yml

To support updating of supervisor without disrupting other deployments, just check to see if supervisor is specified in the non-legacy `server_requirements.txt`.
Remove this conditional following the merging of both upgrades to master.

Supervisord upgrade conditional

---

broker-deploy/app-instance-image.yml
usaspending-deploy/usaspending-api-image.yml

For some reason USAspending and Broker were out-of-sync with how they were handling the credential copy.
Fixing that, along with some text/comment parity.

Revert to shell script

---

usaspending-deploy/usaspending-api-image.yml
usaspending-deploy/usaspending-api-launch.yml

Follows up on api changes made in https://github.com/fedspendingtransparency/usaspending-api/pull/2151

Override HOST value in usaspending-api in order to allow for permalinks.

---

usaspending-deploy/usaspending-api-image.yml
usaspending-deploy/usaspending-api-launch.yml

This was mistakenly removing `$http_user_agent` from the log format and adding `user ec2-user;` in the wrong place this is happening in all environments
you can see it in all environment except sandbox!

fixing regex

---

broker-deploy/app-instance-launch.yml

**Description**
Fixing logic that should disable the apm collection in the the dev environment for broker. 
**Technical Details**
See comment in the code change

[OPS-1034] Disable broker datadog agent apm collection if dev env

---

Dockerfile

Change the default version so that 0.12.24 is used for deployments
NOTES:
BEFORE MERGING:
```
docker build -t data-act-build-tools .
docker run -i --rm=true -v $(pwd):/tmp -w /tmp data-act-build-tools /bin/sh -c "terraform fmt -check -diff -recursive"
docker run -i --rm=true -v $(pwd):/tmp -w /tmp data-act-build-tools \
/bin/sh -c \
"cd broker-deploy; \
terraform init -backend=false; \
terraform validate"
docker run -i --rm=true -v $(pwd):/tmp -w /tmp data-act-build-tools \
/bin/sh -c \
"cd usaspending-deploy; \
terraform init -backend=false; \
terraform validate"
```

[OPS-1194] Upgrade Terraform to version 0.12.24

---

Dockerfile

**High Level Description**
Build containers hosting different versions of build tools
**Technical Details**
- Set default version values as `ARG` entries
- Set `ENV` values to use `ARG` values
- Allows override during docker image build using `--build-arg arg_name=arg_value`

Allow override of built tools versions

---

Dockerfile

This is required to support the `galaxy_file` argument for the ansible packer provisioner, which is being used for logstash ami builds in `data-act-config`.

Upgrade packer to 1.4.3

---

usaspending-deploy/usaspending-api-launch.yml

Set default db timeout for API
The variable is added to the `ansible-vars-[env].yml` https://github.com/fedspendingtransparency/usaspending-config/pull/675

Set DEFAULT_DB_TIMEOUT_IN_SECONDS in settings.py

---

Dockerfile

`centost:latest` is now 8 and building either for the first time or with no previously cached base image fails.
if building for the first time:
```shell
docker build .
```
if building when you already have the centos image layer cached:
```shell
docker build --no-cache .
```
we reference rpms that are specific to centos 7. We need to explicitly call out `centos:7` as the base image now that 8 has been released.
In the future we also need to sort out the python versions and the equivalent epel repo location for `centos:8`.

using centos:latest (now 8), building with no previously cached layers fails

---

Dockerfile

HCL2 support has been released so in order to use HCL packer build files we need to upgrade.

updating packer version

---

Dockerfile

now that we are beginning to use terragrunt as a light wrapper around terraform, we need to install it in our build tools docker container.

adding terragrunt to build tools

---

usaspending-deploy/usaspending-api-image.yml
usaspending-deploy/usaspending-deploy.py

adding cron to USASpending API to manage asg lifecycle.
I also adjusted the usaspending packer + ansible build process to use files from the branches selected in the pipeline instead of always using master. This will make it easier for us in the future as well since the status-quo for testing was to make one-off changes to the ansible scripts so they would pull from the correct branch.

[OPS-1259] adding cron to USASpending API to manage asg lifecycle

---

usaspending-deploy/usaspending-deploy.tf

Just realized I screwed up the queue metric and used sum instead of maximum. It basically set the sum at 5 instances indefinitely, but when I tested in sandbox, I blasted the queue with a ton of messages scaling still worked. I scaled up prod for now just in case we get blasted again.

ops-1001 - moved from sum to max in queue metric

---

Dockerfile

now that we are packaging a lambda function as part of terragrunt deployment, we need npm / nodejs in the build tools container.

Add nodejs to build tools

---

invalidate-url.py

Adding the ability to specify paths if we need to invalidate only a single file or pattern, instead of the whole distribution. The default behavior will not change how this script functions currently.

adding optional path to cloudfront invalidation script

---

Dockerfile

- The IUS repos have moved the IUS version of Python to the archive repo. This silent change has caused the most recent version of Python to be installed and has not been tested. 
- This change forces the IUS repo to install python36u. 
Additional changes
- Adding terragrunt drift detector and static code analysis dependencies

[OPS-1903] Update IUS repo in build-tools container

---

Dockerfile

The build-tools container occasionally fails to build due to the public mirrors not being whitelisted. I moved the container to only use official centos mirrors.

Fix - have the build-tools container only use centos mirros
